packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react-native-reanimated@4.6.0
